# Final Digits of each Quarter Analysis

We will start by modeling the historical data of scores. For simplicity, we will look at the final digits of scores for each quarter.

In [2]:
import pandas as pd
import altair as alt

In [20]:
qtr = pd.read_csv('quarters.csv')
qtr

,season,week,game_date,team,place,qtr1,qtr2,qtr3,qtr4,ot,spread_line,total_line,half,full
0,2013,1,2013-09-05,BAL,away,7,10,0,10,NaN,7.5,48.5,17,27
1,2013,1,2013-09-05,DEN,home,0,14,21,14,NaN,7.5,48.5,14,49
2,2013,1,2013-09-08,ARI,away,0,10,14,0,NaN,3.5,42.5,10,24
3,2013,1,2013-09-08,LA,home,0,10,3,14,NaN,3.5,42.5,10,27
4,2013,1,2013-09-08,ATL,away,10,0,7,0,NaN,3.5,54.5,10,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5745,2023,12,2023-11-23,SEA,home,3,0,10,0,NaN,-7.0,43.5,3,13
5746,2023,12,2023-11-23,WAS,away,0,10,0,0,NaN,13.0,48.0,10,10
5747,2023,12,2023-11-23,DAL,home,7,13,0,25,NaN,13.0,48.0,20,45
5748,2023,12,2023-11-24,MIA,away,3,14,3,14,NaN,-9.5,40.0,17,34
5749,2023,12,2023-11-24,NYJ,home,0,6,0,7,NaN,-9.5,40.0,6,13

We will make a dataframe containing the last digit of scores for each quarter. Put these dataframes into a list called q. We will also make a list of strings to pull from.

In [5]:
strings = ['qtr1','qtr2','qtr3','qtr4','ot']
q = [0]*(len(strings)+1)

for i in range(1,len(strings)+1):
    q[i] = pd.DataFrame((qtr[strings[i-1]]%10).value_counts().sort_index()).reset_index()

For each quarter, we will make a bar chart with the numbers 0 to 9 on the x-axis. On the y axis, we will record the frequency that a final scores has a last digit with the number on the x-axis.

In [6]:
quarters = [q[1],q[2],q[3],q[4],q[5]]
quarter = [0]*(len(quarters)+1)
colors = ['darkred','darkblue','darkorange','purple','darkgreen']

for i in range(1,len(quarters)+1):
    quarter[i] = alt.Chart(quarters[i-1]).mark_bar().encode(
        x = alt.X(f'{strings[i-1]}:N',axis=alt.Axis(labelAngle=0), title = 'Squares'),
        y = alt.Y('count', title = 'Frequency'),
        tooltip= strings[i-1],
        color = alt.value(colors[i-1])
    ).properties(
        title = f'Quarter {i}',
        height=300,
        width=600,
    )
quarter[5] = quarter[5].properties(title = 'Overtime')

In [7]:
alt.vconcat(quarter[1], quarter[2], quarter[3], quarter[4], quarter[5])

alt.VConcatChart(...)